name:                postbank2csv
version:             0.1.0.0
github:              "maxdiefenbach/postbank2csv"
license:             BSD3
author:              "Maximilian N. Diefenbach"
maintainer:          "maxdiefenbach@protonmail.com"
copyright:           "Copyright (c) 2020 Maximilian N. Diefenbach"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxdiefenbach/postbank2csv#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - cassava
  - directory
  - filepath
  - megaparsec
  - process
  - text
  - time

library:
  source-dirs: src

executables:
  postbank2csv:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postbank2csv

tests:
  postbank2csv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postbank2csv
